Removing comment
12358-lab/my-portfolio pull request #29
Opened 2020-02-04 21:09 UTC by 12358-lab

https://github.com/12358-lab/my-portfolio/issues/4

2020-02-05 13:05 UTC, ndiaz-candido commented on src/navigation/CustomLink/CustomLink.js
> +  // This is the key!
Quiza en el ejemplo / articulo este comentario tenga sentido pero ya no lo necesitas, ya tu sabes cual es la clave!

2020-02-05 13:06 UTC, ndiaz-candido commented on src/navigation/CustomLink/CustomLink.js
> +    // If target prop is set (e.g. to "_blank"), let browser handle link.
Este comentario si tiene sentido

2020-02-05 13:06 UTC, ndiaz-candido commented on src/navigation/CustomLink/CustomLink.js
> +  const history = useHistory();
Solo para que lo tengas presenta, `useHistory` es un hook. Ya los estas usando :)

2020-02-05 13:07 UTC, nestor-diaz requested changes
Remover comentario

2020-02-09 18:15 UTC, 12358-lab commented on src/navigation/CustomLink/CustomLink.js
> +  // This is the key!
Removido

2020-02-09 18:20 UTC, merged